name: scan-sign

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

env:
  TRIVY_VEX: ./cves/cve-medium.json
  IMAGE: ttl.sh/knabben/doc-poc

jobs:
  #tests:
  #  uses: ./.github/workflows/test.yml
  build:
    outputs:
      image: ${{ steps.build.outputs.image }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        id: build
        run: |
          image=${IMAGE}:${GITHUB_SHA} 
          docker build -t ${image} .
          docker push ${image}
          echo "image=${image}" >> $GITHUB_OUTPUT
  cve-scan:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build.outputs.image }}
          format: cyclonedx
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
          scanners: 'vuln'
          output: 'project.sbom.json'
      - name: Upload trivy report as a Github artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: '${{ github.workspace }}/project.sbom.json'
          retention-days: 1