name: cve-scan

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

env:
  TRIVY_VEX: cves/cve-medium.json

jobs:
  tests:
    uses: ./.github/workflows/test.yml
  trivy:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        id: build
        run: |
          IMAGE=ttl.sh/knabben/doc-poc:${GITHUB_SHA}
          docker build -t ${IMAGE} .
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.build.outputs.image }}
          format: cyclonedx
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
          scanners: 'vuln'
          output: 'project.sbom.json'
      - name: Upload trivy report as a Github artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: '${{ github.workspace }}/project.sbom.json'
          retention-days: 1