# Run the unit tests from the project
name: Unit Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Checkout the codebase and install Golang for testing
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Golang
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.x
        cache-dependency-path: |
          **/go/sum
          **/go.mod

    # Run unit tests
    - id: test
      run: |
        make test