name: test

on:
  push:
    branches:
      - '**'

permissions:
  content: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
          cache-dependency-path: |
            **/go/sum
            **/go.mod
      - name: Run unit tests
        run: make test